;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        delete-indentation
        down-list
        electric-newline-and-maybe-indent
        electric-pair-delete-pair
        exit-recursive-edit
        forward-sexp
        gud-tooltip-mouse-motion
        handle-switch-frame
        insert-register
        isearch-forward-regexp
        keyboard-escape-quit
        kill-region
        markdown-exdent-or-delete
        newline-and-indent-expanded
        org-self-insert-command
        python-nav-forward-block
        toggle-camel-case-at-point
        toggle-input-method
        yaml-electric-backspace
        yaml-electric-dash-and-dot
        yank-rectangle
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        mouse-drag-mode-line
        mouse-minor-mode-menu
        ))
