;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        c-electric-brace
        c-electric-colon
        c-electric-delete-forward
        c-electric-lt-gt
        c-electric-paren
        c-electric-semi&comma
        c-electric-slash
        c-electric-star
        delete-indentation
        down-list
        electric-newline-and-maybe-indent
        electric-pair-delete-pair
        exit-recursive-edit
        fill-paragraph
        forward-sexp
        gud-tooltip-mouse-motion
        handle-switch-frame
        indent-for-tab-command
        indent-new-comment-line
        insert-register
        isearch-forward-regexp
        keyboard-escape-quit
        kill-region
        markdown-exdent-or-delete
        newline-and-indent-expanded
        org-self-insert-command
        picture-self-insert
        python-indent-shift-left
        python-indent-shift-right
        python-nav-forward-block
        query-replace
        query-replace-regexp
        sh-assignment
        toggle-camel-case-at-point
        toggle-input-method
        yaml-electric-backspace
        yaml-electric-dash-and-dot
        yank-rectangle
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        describe-key
        mouse-drag-mode-line
        mouse-minor-mode-menu
        scroll-right
        where-is
        ))
